"""Stable configuration and provider constants."""

import tempfile
from pathlib import Path

# Container services bind here, while Compose publishes only to host loopback.
DEFAULT_LISTEN_HOST = "0.0.0.0"  # noqa: S104  # nosec B104
DEFAULT_LISTEN_PORT = 8080
DEFAULT_LOG_FILE = Path(tempfile.gettempdir()) / "decidealot.log"
MODEL_DATA_DIRECTORY = Path("/models")
DEFAULT_DEVICE = "cpu"
DEFAULT_IMAGE_VARIANT = "cpu"
IMAGE_VARIANT_METADATA_PATH = Path("/etc/decidealot/image-variant")
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 120.0
DEFAULT_PROVIDER_START_TIMEOUT_SECONDS = 180.0
DEFAULT_PROVIDER_IDLE_UNLOAD_SECONDS = 600.0
DEFAULT_MAX_RESIDENT_LOCAL_PROVIDERS = 1
MAX_LOCAL_PROVIDERS = 3
DEFAULT_MAX_BATCH_REQUESTS = 0
DEFAULT_MAX_BATCH_CONCURRENCY = 0
DEFAULT_MAX_REQUEST_BYTES = 1_048_576
DEFAULT_MCP_ALLOWED_HOSTS = (
    "127.0.0.1,127.0.0.1:*,localhost,localhost:*,[::1],[::1]:*,decidealot,decidealot:*"
)
DEFAULT_MCP_ALLOWED_ORIGINS = "http://127.0.0.1:*,http://localhost:*,http://[::1]:*"
PROCESS_STOP_TIMEOUT_SECONDS = 10.0
MIN_IDLE_REAPER_INTERVAL_SECONDS = 0.01
MAX_IDLE_REAPER_INTERVAL_SECONDS = 30.0
LAYA_PROVIDER_NAME = "laya"
VON_PROVIDER_NAME = "von"
CLM_PROVIDER_NAME = "clm"
JEV_PROVIDER_NAME = "jev"
LAYA_HOST = "127.0.0.1"
VON_HOST = "127.0.0.1"
CLM_HOST = "127.0.0.1"
LAYA_PORT = 8011
VON_PORT = 8012
CLM_PORT = 8013
LAYA_HEALTH_URL = f"http://{LAYA_HOST}:{LAYA_PORT}/health"
VON_HEALTH_URL = f"http://{VON_HOST}:{VON_PORT}/health"
CLM_HEALTH_URL = f"http://{CLM_HOST}:{CLM_PORT}/health"
LAYA_SYSTEMONE_URL = f"http://{LAYA_HOST}:{LAYA_PORT}/v1/systemone"
VON_SYSTEMONE_URL = f"http://{VON_HOST}:{VON_PORT}/v1/systemone"
CLM_SYSTEMONE_URL = f"http://{CLM_HOST}:{CLM_PORT}/v1/systemone"
JEV_SYSTEMONE_URL = "https://api.typesafe.ai/v1/systemone"
JEV_MODELS_URL = "https://api.typesafe.ai/v1/models"
HOSTED_MODEL_CATALOG_TTL_SECONDS = 60.0
TORCH_VENV_DIRECTORY = "/opt/torch-venv"
LAYA_VENV_COMMAND = f"{TORCH_VENV_DIRECTORY}/bin/laya-serve"
LAYA_VENV_PYTHON = f"{TORCH_VENV_DIRECTORY}/bin/python"
CLM_VENV_PYTHON = LAYA_VENV_PYTHON
VON_VENV_COMMAND = f"{TORCH_VENV_DIRECTORY}/bin/von"
VON_VENV_PYTHON = f"{TORCH_VENV_DIRECTORY}/bin/python"
LOCAL_PROVIDER_ENTRYPOINT = "/opt/decidealot/provider_entrypoint.py"
PROVIDER_ENTRYPOINT_PREPARE_ACTION = "prepare"
HF_HUB_OFFLINE = "1"
TRANSFORMERS_OFFLINE = "1"
VON_BACKEND = "von-1.1"
CLM_MODEL_REPOSITORY = "Contrastive-LM/CLM-v0.1-8B"
CLM_MODEL_REVISION = "e939398d4556fcd9400c76fa8c5a513202f42b0a"
CLM_MODEL_FILENAME = "CLM_v0.1-8B.pt"
CLM_MODEL_SHA256 = "b2b4a8c9c2d39263eff78a351eb909a342ce9b3bf21a3f07c1d1bf15f1c4eda5"
CLM_EMBEDDING_DIMENSIONS = 4096
DEFAULT_CLM_EMBEDDINGS_MODEL = "qwen3-8b"
DEFAULT_CLM_EMBEDDINGS_TIMEOUT_SECONDS = 120.0
DEFAULT_CLM_CANDIDATE_CACHE_ENTRIES = 1024
DEFAULT_CLM_CANDIDATE_CACHE_TTL_SECONDS = 600.0
DEFAULT_CLM_MAX_TEXT_BYTES = 8192
REQUEST_ID_HEADER = "X-Request-Id"
BEARER_PREFIX = "Bearer "
MAX_REQUEST_ID_LENGTH = 64
SYSTEMONE_PATH = "/v1/systemone"
SYSTEMONE_BATCH_PATH = "/v1/systemone/batch"
MODELS_PATH = "/v1/models"
MODELS_UNLOAD_PATH = "/v1/models/unload"
HEALTH_PATH = "/health"
MCP_PATH = "/mcp"
MCP_SERVER_NAME = "decidealot"
ERROR_CODE_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_CODE_UNAUTHORIZED = "UNAUTHORIZED"
ERROR_CODE_PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
ERROR_CODE_PROVIDER_BUSY = "PROVIDER_BUSY"
ERROR_CODE_REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
